version: "3.7"
services:
  
  # Controller node is where ansible will be installed through bootstrap.sh
  # Image will be created with name "anslab/controller:v1"
  # container will be created with name "controller"
  controller:
    build: 
      context: .
      dockerfile: ubuntu/Dockerfile
    image: anslab/controller:v1
    container_name: controller
    volumes:
      - /home/karthick/Karthick_Root/Work/Ansible/vagrant_lab_sync/playbooks:/project
    networks:
      - ansible_network
    pull_policy: build

  # Managed node is based on the image created from controller
  # container will be created with name "managed1"
  managed1:
    image: anslab/controller:v1
    container_name: managed1
    networks:
      - ansible_network
    depends_on:
      - controller
    pull_policy: never

networks:
  ansible_network:
    driver: bridge
    name: anslab